# Generated by Django 4.0.6 on 2022-08-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRecipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('units', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('recipes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
