# Generated by Django 4.0.6 on 2022-08-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_scrapedrecipes_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedrecipes',
            options={'managed': False},
        ),
    ]
