# Generated by Django 4.0.6 on 2022-08-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_scrapedrecipes_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapedrecipes',
            table='scraped_recipes',
        ),
    ]
