# Generated by Django 4.0.6 on 2022-08-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_scrapedrecipes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapedrecipes',
            table='recipe_table',
        ),
    ]
