# Generated by Django 4.0.6 on 2022-08-09 23:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_scrapedrecipes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.TextField(blank=True, null=True)),
                ('amount', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('units', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('recipes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'recipe_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ScrapedRecipes',
        ),
    ]
