# Generated by Django 4.0.6 on 2022-08-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_scraped_delete_scrapedrecipes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraped',
            table='scraped_recipes',
        ),
    ]
